#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Relay's Google Cloud / HuggingFace / Groq provisioning.
#
# Everything this script CAN do without you (local Postgres container,
# Qdrant reuse, AES-256-GCM encryption key, HMAC state-signing secret) was
# already done directly and written to .env.local before this wizard was
# generated — see .env.local for DATABASE_URL, QDRANT_URL,
# RELAY_ENCRYPTION_KEY, RELAY_STATE_SECRET. This wizard only covers the
# parts that genuinely require your own accounts in a browser.
# ──────────────────────────────────────────────────────────────────────────

# Absolute path to relay/.env.local, regardless of which directory this
# script is invoked from (a relative ".env.local" here previously wrote to
# wherever the caller's cwd happened to be, not the project root).
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env.local"
TOTAL_STAGES=6

banner "Relay: Google Workspace + AI provider setup"

# ── Stage 1: Google Cloud project + enable the 5 Workspace APIs ───────────
stage "Google Cloud: create a project and enable APIs"
say "Relay needs its own Google Cloud project with Drive, Docs, Gmail, Calendar,"
say "and Sheets APIs enabled (read-only scopes only — see PRD §4.1)."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a new project (e.g. name it 'relay-dev') and make sure it's the"
step "SELECTED project in the top-left project switcher before continuing —"
step "every link below acts on whichever project is currently selected."
pause "Project created and selected?"

say "Now enable each API this project touches. Click 'Enable' on each page"
say "(if it already says 'Manage', it's already enabled — just move on)."
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com"
pause "Drive API enabled?"
open_url "https://console.cloud.google.com/apis/library/docs.googleapis.com"
pause "Docs API enabled?"
open_url "https://console.cloud.google.com/apis/library/gmail.googleapis.com"
pause "Gmail API enabled?"
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
pause "Calendar API enabled?"
open_url "https://console.cloud.google.com/apis/library/sheets.googleapis.com"
pause "Sheets API enabled?"

# ── Stage 2: OAuth consent screen (External, testing, minimal scopes) ─────
stage "Google Cloud: OAuth consent screen"
say "This app requests 'restricted' scopes (drive.readonly, gmail.readonly)."
say "For an unverified app in Testing mode, up to 100 explicit test users can"
say "still use it without Google's full verification review — that's the"
say "deliberate v1 scoping this project documents in PRD §6.4/§8, not an"
say "oversight. Do NOT attempt to publish this app to Production."
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "User type: choose 'External' (unless this is a Workspace account and"
step "you'd rather choose 'Internal', which skips the test-user list entirely)."
step "App name: Relay. User support email + developer contact: your own email."
step "On the Scopes step, click 'Add or Remove Scopes' and add exactly:"
step "  openid, .../auth/userinfo.email, .../auth/drive.readonly,"
step "  .../auth/gmail.readonly, .../auth/calendar.readonly,"
step "  .../auth/spreadsheets.readonly"
step "(These match lib/google/scopes.ts exactly — don't add broader scopes"
step "like drive.file or gmail.modify; this app never needs write access.)"
step "On the Test users step, add the Google account you'll actually connect"
step "Relay to — this becomes RELAY_OWNER_EMAIL below."
ask RELAY_OWNER_EMAIL "Which Google account did you add as a test user (your email):"
write_env RELAY_OWNER_EMAIL "$RELAY_OWNER_EMAIL"
pause "Consent screen saved, with that email added as a test user?"

# ── Stage 3: OAuth Client ID (Web application) ─────────────────────────────
stage "Google Cloud: OAuth Client ID"
open_url "https://console.cloud.google.com/apis/credentials"
step "Click '+ Create Credentials' → 'OAuth client ID'."
step "Application type: Web application. Name: Relay (or anything)."
step "Under 'Authorized redirect URIs', add EXACTLY:"
step "  http://localhost:3000/api/auth/google/callback"
step "(This must match GOOGLE_REDIRECT_URI in .env.local character-for-character"
step "— lib/google/oauth.ts sends this exact value on every request.)"
step "Click Create. A dialog shows the Client ID and Client Secret — copy both."
ask GOOGLE_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client Secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
warn "Client Secret is now in .env.local, which is gitignored — never commit it."

# ── Stage 4: Hugging Face Inference API token ──────────────────────────────
stage "Hugging Face: Inference API token"
say "Used for embeddings (BAAI/bge-small-en-v1.5) and reranking (BAAI/bge-reranker-v2-m3), same embedding model"
say "as this portfolio's Mimo project — see lib/rag/embed.ts and rerank.ts."
open_url "https://huggingface.co/settings/tokens"
step "Create new token → Type: 'Read' is sufficient (this only calls the"
step "public Inference API, it doesn't need write/repo access)."
ask_secret HF_TOKEN "Paste the token:"
write_env HF_TOKEN "$HF_TOKEN"

# ── Stage 5: Groq API key ──────────────────────────────────────────────────
stage "Groq: API key"
say "Used for generation (openai/gpt-oss-120b) — see lib/rag/generate.ts."
open_url "https://console.groq.com/keys"
step "Create API Key, then copy it (Groq only shows it once)."
ask_secret GROQ_API_KEY "Paste the key:"
write_env GROQ_API_KEY "$GROQ_API_KEY"

# ── Stage 6: Upstash QStash (background ingestion jobs) ───────────────────
stage "Upstash: QStash token + signing keys"
say "Backfill/sync currently run synchronously in the request cycle (see"
say "app/api/ingest/backfill/route.ts) — fine for local dev, not for a large"
say "real Drive. QStash is the background-job queue that fixes that, same"
say "pattern already used in this portfolio's What To Do project."
say "The free tier is more than enough for this project's volume."
open_url "https://console.upstash.com"
step "Sign up or log in (GitHub/Google sign-in both work)."
pause "Logged in to the Upstash console?"

open_url "https://console.upstash.com/qstash"
step "This is the QStash overview page — your credentials are shown right"
step "there: a 'QSTASH_TOKEN', and under 'Signing Keys', a current and a"
step "next signing key. No separate 'create' step; they exist by default."
ask_secret QSTASH_TOKEN "Paste QSTASH_TOKEN:"
write_env QSTASH_TOKEN "$QSTASH_TOKEN"
step "Now the signing keys — QStash rotates these, so the receiving endpoint"
step "has to check a request's signature against BOTH before rejecting it."
ask_secret QSTASH_CURRENT_SIGNING_KEY "Paste the Current signing key:"
write_env QSTASH_CURRENT_SIGNING_KEY "$QSTASH_CURRENT_SIGNING_KEY"
ask_secret QSTASH_NEXT_SIGNING_KEY "Paste the Next signing key:"
write_env QSTASH_NEXT_SIGNING_KEY "$QSTASH_NEXT_SIGNING_KEY"

warn "QStash calls back into a job-receiving endpoint over the public"
warn "internet — it can't reach http://localhost directly. That only"
warn "matters once that endpoint actually exists; for local testing at that"
warn "point, tunnel it first (e.g. 'ngrok http 3000', or Upstash's own CLI"
warn "dev proxy) and use the tunnel's https URL, not localhost, when"
warn "registering the job."

finish

say "Next: from the relay/ directory —"
say "  npm run db:push   # applies lib/db/schema.ts to your local Postgres"
say "  npm run dev       # then open http://localhost:3000/connections"
say ""
warn "First OAuth connect will show Google's 'unverified app' warning screen —"
warn "expected for a Testing-mode app (PRD §6.4). Click 'Advanced' → 'Go to"
warn "Relay (unsafe)' to proceed; this is safe because it's YOUR OWN app."
say ""
say "QSTASH_TOKEN / QSTASH_CURRENT_SIGNING_KEY / QSTASH_NEXT_SIGNING_KEY are"
say "now in .env.local, ready for the background-job wiring that reads them."
